#!/usr/bin/env bash
# House of Refuge — one-time email notification setup.
#
# Prompts for the Zoho app password, generates the webhook secret, pushes both
# to Supabase as function secrets, deploys the two mail functions, and writes
# the SQL you paste into the SQL editor.
#
# Nothing secret is echoed to the terminal or committed. Run from the repo root:
#   ./supabase/setup-email.sh

set -euo pipefail

PROJECT_REF="${PROJECT_REF:-fllfmifzfwlkigscgnah}"
APP_URL="https://www.houseofrefugeng.org"
OUT="$(cd "$(dirname "$0")" && pwd)/.enable-notifications.local.sql"

# Prefer a real install; fall back to npx. (Homebrew's formula wants to build
# from source on this machine, which needs newer Xcode Command Line Tools.)
if command -v supabase >/dev/null; then
  SB() { supabase "$@"; }
else
  echo "supabase CLI not installed; using npx (first run downloads the binary)."
  SB() { npx --yes supabase@latest "$@"; }
fi

echo "House of Refuge — email notification setup"
echo "Project: $PROJECT_REF"
echo

# ── 1. Collect inputs ─────────────────────────────────────
read -r -p "Zoho sending mailbox [contact@houseofrefugeng.org]: " ZOHO_USER
ZOHO_USER="${ZOHO_USER:-contact@houseofrefugeng.org}"

read -r -s -p "Zoho APP-SPECIFIC password (input hidden): " ZOHO_PASS
echo
[ -n "$ZOHO_PASS" ] || { echo "A password is required."; exit 1; }

echo
echo "Who should receive internal alerts for every new submission?"
read -r -p "Comma-separated addresses: " STAFF_EMAILS
[ -n "$STAFF_EMAILS" ] || { echo "At least one staff address is required."; exit 1; }

read -r -p "Zoho SMTP host [smtp.zoho.com]: " ZOHO_HOST
ZOHO_HOST="${ZOHO_HOST:-smtp.zoho.com}"

WEBHOOK_SECRET="$(openssl rand -hex 32)"

# ── 2. Link + push secrets ────────────────────────────────
echo
if ! SB projects list >/dev/null 2>&1; then
  echo "→ Not signed in to Supabase. Opening the browser to authorise..."
  SB login
fi

echo "→ Linking project..."
# The CLI may ask for the database password here; it is only needed for schema
# commands, so pressing Enter to skip is fine for this setup.
SB link --project-ref "$PROJECT_REF" >/dev/null

echo "→ Setting function secrets..."
SB secrets set \
  ZOHO_SMTP_USER="$ZOHO_USER" \
  ZOHO_SMTP_PASSWORD="$ZOHO_PASS" \
  ZOHO_SMTP_HOST="$ZOHO_HOST" \
  NOTIFY_WEBHOOK_SECRET="$WEBHOOK_SECRET" \
  NOTIFY_STAFF_EMAILS="$STAFF_EMAILS" \
  PUBLIC_APP_URL="$APP_URL" >/dev/null
echo "  secrets set."

# ── 3. Deploy ─────────────────────────────────────────────
echo "→ Deploying send-notification (no JWT: pg_net calls it from the DB)..."
SB functions deploy send-notification --no-verify-jwt

echo "→ Deploying send-deposit-request..."
SB functions deploy send-deposit-request

# ── 4. Emit the SQL to switch it on ───────────────────────
cat > "$OUT" <<SQL
-- Generated by setup-email.sh. Contains the webhook secret: do not commit.
-- Run AFTER 20260810_email_notifications.sql.
update private.notification_config set
  function_url   = 'https://$PROJECT_REF.supabase.co/functions/v1/send-notification',
  webhook_secret = '$WEBHOOK_SECRET',
  enabled        = true
where id = 1;

select enabled, function_url from private.notification_config where id = 1;
SQL
chmod 600 "$OUT"

echo
echo "Done. Final step, in the Supabase SQL editor:"
echo "  1. Run supabase/migrations/20260810_email_notifications.sql"
echo "  2. Then run the contents of:"
echo "     $OUT"
echo
echo "That file holds the webhook secret. It is gitignored; delete it once run."
