#!/usr/bin/env bash
# House of Refuge — one-time email notification setup.
#
# Prompts for the Zoho app password, generates the webhook secret, pushes both
# to Supabase as function secrets, deploys the two mail functions, and writes
# the SQL you paste into the SQL editor.
#
# Nothing secret is echoed to the terminal or committed. Run from the repo root:
#   ./supabase/setup-email.sh

set -euo pipefail

PROJECT_REF="${PROJECT_REF:-fllfmifzfwlkigscgnah}"
APP_URL="https://www.houseofrefugeng.org"
OUT="$(cd "$(dirname "$0")" && pwd)/.enable-notifications.local.sql"

# Prefer a real install; fall back to npx. (Homebrew's formula wants to build
# from source on this machine, which needs newer Xcode Command Line Tools.)
if command -v supabase >/dev/null; then
  SB() { supabase "$@"; }
else
  echo "supabase CLI not installed; using npx (first run downloads the binary)."
  SB() { npx --yes supabase@latest "$@"; }
fi

echo "House of Refuge — email notification setup"
echo "Project: $PROJECT_REF"
echo

# ── 1. Collect inputs ─────────────────────────────────────
# Read from the terminal, not stdin. A pasted value carries a trailing newline,
# and that newline used to satisfy the NEXT read instantly: the staff-address
# prompt would flash past unanswered and the script aborted. Reading from
# /dev/tty and re-prompting on empty makes a stray newline harmless.
TTY=/dev/tty
[ -r "$TTY" ] || TTY=/dev/stdin

# Every value can be preset in the environment to skip its prompt entirely:
#   ZOHO_USER=me@x.org ZOHO_PASS=... STAFF_EMAILS=a@x.org ./supabase/setup-email.sh
ask() {           # ask VAR "prompt" "default"   (empty default = required)
  local __var="$1" __prompt="$2" __default="${3:-}" __val
  __val="${!__var:-}"
  while [ -z "$__val" ]; do
    printf '%s' "$__prompt" > "$TTY"
    IFS= read -r __val < "$TTY" || __val=""
    __val="${__val#"${__val%%[![:space:]]*}"}"   # trim leading space
    __val="${__val%"${__val##*[![:space:]]}"}"   # trim trailing space
    if [ -z "$__val" ] && [ -n "$__default" ]; then __val="$__default"; fi
    [ -n "$__val" ] || echo "  This one is required - please type a value." > "$TTY"
  done
  printf -v "$__var" '%s' "$__val"
}

ask ZOHO_USER "Zoho sending mailbox [contact@houseofrefugeng.org]: " "contact@houseofrefugeng.org"

# Zoho displays app passwords in spaced groups; the spaces are not part of it.
while [ -z "${ZOHO_PASS:-}" ]; do
  printf 'Zoho APP-SPECIFIC password for %s (input hidden): ' "$ZOHO_USER" > "$TTY"
  IFS= read -r -s ZOHO_PASS < "$TTY" || ZOHO_PASS=""
  echo > "$TTY"
  [ -n "$ZOHO_PASS" ] || echo "  A password is required." > "$TTY"
done
# Strip unconditionally, so a preset ZOHO_PASS= is cleaned the same way a typed
# one is. Zoho renders the password in spaced groups and those spaces are not
# part of it; sending them produces an SMTP auth failure that reads like a
# wrong password.
ZOHO_PASS="${ZOHO_PASS//[[:space:]]/}"

echo
echo "Who should receive internal alerts for every new submission?"
ask STAFF_EMAILS "Comma-separated addresses: "

ask ZOHO_HOST "Zoho SMTP host [smtp.zoho.com]: " "smtp.zoho.com"

echo
echo "Sending as : $ZOHO_USER"
echo "Alerting   : $STAFF_EMAILS"
echo "SMTP host  : $ZOHO_HOST"
echo

WEBHOOK_SECRET="$(openssl rand -hex 32)"

# ── 2. Link + push secrets ────────────────────────────────
echo
if ! SB projects list >/dev/null 2>&1; then
  echo "→ Not signed in to Supabase. Opening the browser to authorise..."
  SB login
fi

echo "→ Linking project..."
# The CLI may ask for the database password here; it is only needed for schema
# commands, so pressing Enter to skip is fine for this setup.
SB link --project-ref "$PROJECT_REF" >/dev/null

echo "→ Setting function secrets..."
SB secrets set \
  ZOHO_SMTP_USER="$ZOHO_USER" \
  ZOHO_SMTP_PASSWORD="$ZOHO_PASS" \
  ZOHO_SMTP_HOST="$ZOHO_HOST" \
  NOTIFY_WEBHOOK_SECRET="$WEBHOOK_SECRET" \
  NOTIFY_STAFF_EMAILS="$STAFF_EMAILS" \
  PUBLIC_APP_URL="$APP_URL" >/dev/null
echo "  secrets set."

# ── 3. Deploy ─────────────────────────────────────────────
echo "→ Deploying send-notification (no JWT: pg_net calls it from the DB)..."
SB functions deploy send-notification --no-verify-jwt

echo "→ Deploying send-deposit-request..."
SB functions deploy send-deposit-request

# ── 4. Emit the SQL to switch it on ───────────────────────
cat > "$OUT" <<SQL
-- Generated by setup-email.sh. Contains the webhook secret: do not commit.
-- Run AFTER 20260810_email_notifications.sql.
update private.notification_config set
  function_url   = 'https://$PROJECT_REF.supabase.co/functions/v1/send-notification',
  webhook_secret = '$WEBHOOK_SECRET',
  enabled        = true
where id = 1;

select enabled, function_url from private.notification_config where id = 1;
SQL
chmod 600 "$OUT"

echo
echo "Done. Final step, in the Supabase SQL editor:"
echo "  Run the contents of:"
echo "     $OUT"
echo
echo "  (20260810_email_notifications.sql is already applied if you have run"
echo "   supabase/RUN_PENDING_2026-08-24.sql. Check with:"
echo "     select tgname from pg_trigger where tgname like 'notify%';"
echo "   Four rows means you are set.)"
echo
echo "That file holds the webhook secret. It is gitignored; delete it once run."
